### ISSUE TITLE
update frontend build instruction?

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#195]
I got the following build errors:

yarn run v1.22.4
$ rimraf dist/ && webpack --watch --mode=development
/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module '@wasm-tool/wasm-pack-plugin'
Require stack:
- /Users/rust/Projects/shengji/frontend/webpack.config.js
- /Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/utils/convert-argv.js
- /Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/cli.js
- /Users/rust/Projects/shengji/frontend/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/rust/Projects/shengji/frontend/webpack.config.js:2:24)
    at Module._compile (/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/rust/Projects/shengji/frontend/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/rust/Projects/shengji/frontend/webpack.config.js',
    '/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/Users/rust/Projects/shengji/frontend/node_modules/webpack-cli/bin/cli.js',
    '/Users/rust/Projects/shengji/frontend/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 1.

**Comment by cai-jack** [comment]
never mind. fixed. need to install the dependencies first
